try {
    let a = 0
    console.log("program run successfully")
    console.log(program)
} catch (error) {
    console.log("this is an error")
    console.log(catchkeandrerror)
}   
finally{
    console.log("i will definitely run")
    console.log("error catch ma ajaye to ma finnaly chal jaounga agr error handle nhi huwa")
}